// Copyright (c) Aspose 2002-2014. All Rights Reserved.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class ExamplesData
{

    private Folder[][] foldersField;

    private Example[][] examplesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Folder", typeof(Folder), IsNullable = false)]
    public Folder[][] Folders
    {
        get
        {
            return this.foldersField;
        }
        set
        {
            this.foldersField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Example", typeof(Example), IsNullable = false)]
    public Example[][] Examples
    {
        get
        {
            return this.examplesField;
        }
        set
        {
            this.examplesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Folder
{

    private string titleField;

    private string descriptionField;

    private string folderNameField;

    private string orderField;

    private List<Example> examplesField;

    private List<Folder> foldersField;

    /// <remarks/>
    public string Title
    {
        get
        {
            return this.titleField;
        }
        set
        {
            this.titleField = value;
        }
    }

    /// <remarks/>
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    public string FolderName
    {
        get
        {
            return this.folderNameField;
        }
        set
        {
            this.folderNameField = value;
        }
    }

    /// <remarks/>
    public string Order
    {
        get
        {
            return this.orderField;
        }
        set
        {
            this.orderField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Example", typeof(Example), IsNullable = false)]
    public List<Example> Examples
    {
        get
        {
            return this.examplesField;
        }
        set
        {
            this.examplesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Folder", typeof(Folder), IsNullable = false)]
    public List<Folder> Folders
    {
        get
        {
            return this.foldersField;
        }
        set
        {
            this.foldersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Example
{

    private string titleField;

    private string descriptionField;

    private string folderNameField;

    private string orderField;

    private DocLink docLinkField;

    private InputFiles inputFilesField;

    private OutputFiles outputFilesField;

    private string typeField;

    /// <remarks/>
    public string Title
    {
        get
        {
            return this.titleField;
        }
        set
        {
            this.titleField = value;
        }
    }

    /// <remarks/>
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    public string FolderName
    {
        get
        {
            return this.folderNameField;
        }
        set
        {
            this.folderNameField = value;
        }
    }

    /// <remarks/>
    public string Order
    {
        get
        {
            return this.orderField;
        }
        set
        {
            this.orderField = value;
        }
    }

    /// <remarks/>
    public DocLink DocLink
    {
        get
        {
            return this.docLinkField;
        }
        set
        {
            this.docLinkField = value;
        }
    }

    /// <remarks/>
    public InputFiles InputFiles
    {
        get
        {
            return this.inputFilesField;
        }
        set
        {
            this.inputFilesField = value;
        }
    }

    /// <remarks/>
    public OutputFiles OutputFiles
    {
        get
        {
            return this.outputFilesField;
        }
        set
        {
            this.outputFilesField = value;
        }
    }

    /// <remarks/>
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class DocLink
{

    private string displayNameField;

    private string urlField;

    /// <remarks/>
    public string DisplayName
    {
        get
        {
            return this.displayNameField;
        }
        set
        {
            this.displayNameField = value;
        }
    }

    /// <remarks/>
    public string Url
    {
        get
        {
            return this.urlField;
        }
        set
        {
            this.urlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class InputFiles
{

    private string[] dataFileField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Path", IsNullable = false)]
    public string[] DataFile
    {
        get
        {
            return this.dataFileField;
        }
        set
        {
            this.dataFileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class OutputFiles
{

    private string[] dataFileField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Path", IsNullable = false)]
    public string[] DataFile
    {
        get
        {
            return this.dataFileField;
        }
        set
        {
            this.dataFileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Folders
{

    private Folder[] folderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Folder")]
    public Folder[] Folder
    {
        get
        {
            return this.folderField;
        }
        set
        {
            this.folderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Examples
{

    private Example[] exampleField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Example")]
    public Example[] Example
    {
        get
        {
            return this.exampleField;
        }
        set
        {
            this.exampleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class DataFile
{

    private string[] pathField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Path")]
    public string[] Path
    {
        get
        {
            return this.pathField;
        }
        set
        {
            this.pathField = value;
        }
    }
}
