name: Update nuget packages
on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  
jobs:
  update_packages:
    runs-on: windows-latest
    steps:
      # Sync branch
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3      

      # Update packages
      - name: Install dependencies ApiExamples
        run: dotnet restore ./Examples/ApiExamples/ApiExamples/ApiExamples.csproj
      - name: Install dependencies DocsExamples
        run: dotnet restore ./Examples/DocsExamples/DocsExamples/DocsExamples.csproj
      - name: update packages
        uses: Bchir/update-nuget@V1.0.0
        with:
          directory: ./Examples/
          searchFor: 'outdated'
          versionToSelect: 'latest'
      
      # Run tests
      - name: Run ApiExamples tests .Net Framework 4.8
        run: dotnet test ./Examples/ApiExamples/ApiExamples/ApiExamples.csproj --framework net48 --configuration Release
      - name: Run ApiExamples tests .Net 6.0
        run: dotnet test ./Examples/ApiExamples/ApiExamples/ApiExamples.csproj --framework net6.0 --configuration Release
      - name: Run DocsExamples tests .Net Framework 4.8
        run: dotnet test ./Examples/DocsExamples/DocsExamples/DocsExamples.csproj --framework net48 --configuration Release
      - name: Run DocsExamples tests .Net 6.0
        run: dotnet test ./Examples/DocsExamples/DocsExamples/DocsExamples.csproj --framework net6.0 --configuration Release
